"use client"

import { useEffect, useState } from "react"
import { Brain } from "lucide-react"
import AIInsightCard from "@/components/ai-insight-card"
import { fetchAIInsights } from "@/lib/api"

export default function AIInsightsPage() {
  const [insights, setInsights] = useState<any[]>([])

  useEffect(() => {
    fetchAIInsights().then((res) => setInsights(res.insights || res))
  }, [])

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-2">
        <Brain className="h-6 w-6" />
        <h1 className="text-2xl font-bold">AI Cost Insights</h1>
      </div>

      <p className="text-sm text-muted-foreground max-w-2xl">
        These insights are generated by analyzing cloud usage metrics and
        applying AI-driven reasoning.
      </p>

      {insights.length === 0 ? (
        <p>Loading AI insights...</p>
      ) : (
        <div className="space-y-4">
          {insights.map((item, index) => (
            <AIInsightCard
              key={index}
              title={item.title}
              severity={item.severity}
              description={item.description}
              recommendation={item.recommendation}
            />
          ))}
        </div>
      )}
    </div>
  )
}
